version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: image-php_to_pgsql
    container_name: merece-container
    restart: always
    working_dir: /var/www
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/www
    depends_on:
      - postgres-service
  nginx:
    image: nginx:1.19-alpine
    container_name: merece-container-nginex
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
  postgres-service:
    image: postgres:latest
    container_name: merece-container-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test1234
    volumes: 
      - ./db:/var/lib/postgresql/data